#!/bin/bash
#===============================================================================
# BITZ CLUB - CLEAN DEPLOYMENT SCRIPT
# Run on: root@139.59.24.136
# This script removes old system and deploys fresh
#===============================================================================

set -e
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}========================================"
echo "BITZ CLUB - CLEAN DEPLOYMENT"
echo -e "========================================${NC}"

PROJECT_DIR="/root/bitzclub"
DOMAIN="thebitzclub.com"

#---------------------------------------
# STEP 1: Stop Old Services
#---------------------------------------
echo -e "\n${YELLOW}[1/8] Stopping old services...${NC}"

# Stop any running node/react dev servers
pkill -f "node.*react" 2>/dev/null || true
pkill -f "npm start" 2>/dev/null || true
pkill -f "yarn start" 2>/dev/null || true

# Stop old backend if running differently
pkill -f "uvicorn.*8000" 2>/dev/null || true

# Stop the backend service (will restart later)
sudo systemctl stop bitz-backend 2>/dev/null || true

echo -e "${GREEN}✓ Old services stopped${NC}"

#---------------------------------------
# STEP 2: Backup Old Build
#---------------------------------------
echo -e "\n${YELLOW}[2/8] Backing up old files...${NC}"

BACKUP_DIR="/root/bitzclub_backup_$(date +%Y%m%d_%H%M%S)"
mkdir -p $BACKUP_DIR

# Backup frontend build
if [ -d "$PROJECT_DIR/frontend/build" ]; then
    cp -r $PROJECT_DIR/frontend/build $BACKUP_DIR/frontend_build
fi

# Backup backend
if [ -f "$PROJECT_DIR/backend/server.py" ]; then
    cp $PROJECT_DIR/backend/server.py $BACKUP_DIR/server.py.backup
fi

# Backup .env files
cp $PROJECT_DIR/backend/.env $BACKUP_DIR/backend.env.backup 2>/dev/null || true
cp $PROJECT_DIR/frontend/.env $BACKUP_DIR/frontend.env.backup 2>/dev/null || true

echo -e "${GREEN}✓ Backup created at: $BACKUP_DIR${NC}"

#---------------------------------------
# STEP 3: Clean Old Frontend Build
#---------------------------------------
echo -e "\n${YELLOW}[3/8] Removing old frontend build...${NC}"

rm -rf $PROJECT_DIR/frontend/build
rm -rf $PROJECT_DIR/frontend/node_modules/.cache

echo -e "${GREEN}✓ Old build removed${NC}"

#---------------------------------------
# STEP 4: Update Backend
#---------------------------------------
echo -e "\n${YELLOW}[4/8] Updating backend...${NC}"

cd $PROJECT_DIR/backend

# Install/update dependencies
pip3 install -r requirements.txt -q

# Ensure LIVE Razorpay keys (check and warn)
if grep -q "rzp_test_" .env 2>/dev/null; then
    echo -e "${RED}⚠ WARNING: TEST Razorpay keys detected!${NC}"
    echo "Updating to LIVE keys..."
    sed -i 's/RAZORPAY_KEY_ID=.*/RAZORPAY_KEY_ID="rzp_live_SSGM9EfgDl6Y8U"/' .env
    sed -i 's/RAZORPAY_KEY_SECRET=.*/RAZORPAY_KEY_SECRET="W6lOWafuYl0Kh8I9WNzeXD3y"/' .env
    echo -e "${GREEN}✓ Razorpay keys updated to LIVE${NC}"
fi

echo -e "${GREEN}✓ Backend updated${NC}"

#---------------------------------------
# STEP 5: Build Frontend Fresh
#---------------------------------------
echo -e "\n${YELLOW}[5/8] Building fresh frontend...${NC}"

cd $PROJECT_DIR/frontend

# Clean install
rm -rf node_modules/.cache 2>/dev/null || true

# Install dependencies
yarn install

# Set environment and build
echo "REACT_APP_BACKEND_URL=https://$DOMAIN" > .env

# Build production
yarn build

echo -e "${GREEN}✓ Frontend built successfully${NC}"

#---------------------------------------
# STEP 6: Configure Nginx (CRITICAL)
#---------------------------------------
echo -e "\n${YELLOW}[6/8] Configuring Nginx...${NC}"

# Create proper nginx config
sudo tee /etc/nginx/sites-available/$DOMAIN > /dev/null << 'NGINXCONFIG'
# BITZ Club - Nginx Configuration
# Auto-generated by deployment script

server {
    listen 80;
    server_name thebitzclub.com www.thebitzclub.com;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name thebitzclub.com www.thebitzclub.com;

    # SSL (Let's Encrypt)
    ssl_certificate /etc/letsencrypt/live/thebitzclub.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/thebitzclub.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    # Frontend - React SPA (CRITICAL: try_files for routing)
    location / {
        root /root/bitzclub/frontend/build;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Backend API
    location /api/ {
        proxy_pass http://127.0.0.1:8001/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
    }

    # Static files caching
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        root /root/bitzclub/frontend/build;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
}
NGINXCONFIG

# Enable site
sudo ln -sf /etc/nginx/sites-available/$DOMAIN /etc/nginx/sites-enabled/
sudo rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true

echo -e "${GREEN}✓ Nginx configured with SPA routing${NC}"

#---------------------------------------
# STEP 7: Clear Cache and Restart Services
#---------------------------------------
echo -e "\n${YELLOW}[7/8] Restarting services...${NC}"

# Clear all caches
sudo rm -rf /var/cache/nginx/*
sync

# Test nginx config
sudo nginx -t

# Restart nginx
sudo systemctl restart nginx

# Restart backend
sudo systemctl restart bitz-backend

# Wait for services to start
sleep 3

echo -e "${GREEN}✓ All services restarted${NC}"

#---------------------------------------
# STEP 8: Verification
#---------------------------------------
echo -e "\n${YELLOW}[8/8] Verifying deployment...${NC}"
echo ""

# Check services
echo "Service Status:"
echo -n "  Backend: "
sudo systemctl is-active bitz-backend && echo -e "${GREEN}running${NC}" || echo -e "${RED}stopped${NC}"
echo -n "  Nginx: "
sudo systemctl is-active nginx && echo -e "${GREEN}running${NC}" || echo -e "${RED}stopped${NC}"

echo ""
echo "Route Verification:"

# Test routes
echo -n "  Homepage (/): "
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://$DOMAIN/)
[ "$HTTP_CODE" = "200" ] && echo -e "${GREEN}$HTTP_CODE OK${NC}" || echo -e "${RED}$HTTP_CODE FAIL${NC}"

echo -n "  Register (/register): "
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://$DOMAIN/register)
[ "$HTTP_CODE" = "200" ] && echo -e "${GREEN}$HTTP_CODE OK${NC}" || echo -e "${RED}$HTTP_CODE FAIL${NC}"

echo -n "  Join (/join): "
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://$DOMAIN/join)
[ "$HTTP_CODE" = "200" ] && echo -e "${GREEN}$HTTP_CODE OK${NC}" || echo -e "${RED}$HTTP_CODE FAIL${NC}"

echo -n "  Admin (/admin): "
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://$DOMAIN/admin)
[ "$HTTP_CODE" = "200" ] && echo -e "${GREEN}$HTTP_CODE OK${NC}" || echo -e "${RED}$HTTP_CODE FAIL${NC}"

echo -n "  Plans API: "
PLANS=$(curl -s https://$DOMAIN/api/plans 2>/dev/null | python3 -c "import sys,json; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "0")
[ "$PLANS" -gt "0" ] && echo -e "${GREEN}$PLANS plans loaded${NC}" || echo -e "${RED}API ERROR${NC}"

echo ""
echo "Razorpay Mode:"
sudo journalctl -u bitz-backend --no-pager -n 20 2>/dev/null | grep -i "razorpay.*initialized" | tail -1 || echo "  Check logs manually"

echo ""
echo -e "${GREEN}========================================"
echo "DEPLOYMENT COMPLETE"
echo -e "========================================${NC}"
echo ""
echo "Test URLs:"
echo "  • https://$DOMAIN/"
echo "  • https://$DOMAIN/register"
echo "  • https://$DOMAIN/join"
echo "  • https://$DOMAIN/admin"
echo ""
echo "Backup location: $BACKUP_DIR"
echo ""
